export const localeText = {
  columnMenuFilter: "Bộ lọc",
  columnMenuSortAsc: "Xắp xếp tăng dần",
  columnMenuSortDesc: "Xắp xếp giảm dần",
  columnMenuHideColumn: "Ẩn cột",
  columnMenuManageColumns: "Quản lý cột",
  columnMenuUnsort: "Huỷ sắp xếp",
  filterPanelInputLabel: "Giá trị lọc",
  filterPanelOperator: "Toán tử...",
  filterPanelColumns: "Cột...",
  filterPanelInputPlaceholder: "Giá trị lọc...",
  filterOperatorEquals: "Bằng",
  filterOperatorDoesNotContain: "Không chứa",
  filterOperatorNotEquals: "Khác",
  filterOperatorGreaterThan: "Lớn hơn",
  filterOperatorGreaterThanOrEqual: "Lớn hơn hoặc bằng",
  filterOperatorLessThan: "Nhỏ hơn",
  filterOperatorLessThanOrEqual: "Nhỏ hơn hoặc bằng",
  filterOperatorContains: "Chứa",
  filterOperatorStartsWith: "Bắt đầu bằng",
  filterOperatorEndsWith: "Kết thúc bằng",
  filterOperatorDoesNotEqual: "Không bằng",
  filterOperatorIsNotEmpty: "Không trống",
  filterOperatorIsEmpty: "Trống",
  filterOperatorIsAnyOf: "Một trong",
  footerRowSelected: (count) => `${count} hàng đã được chọn`,
  toolbarExport: "Xuất dữ liệu",
  toolbarExportCSV: "Xuất CSV",
  toolbarExportPrint: "In",
  toolbarDensity: "Độ rộng hàng",
  toolbarDensityCompact: "Nhỏ",
  toolbarDensityStandard: "Vừa",
  toolbarDensityComfortable: "Rộng",
}
